
import os
from random import choice

hints = [
    "Roll at disadvantage with 2d20kl1",
    "Combine dice with arithmetics 1d20 * 4",
    "The rolls 1d20+5 and 1d20 +5 are not the same.",
    "Creating a new D&D char? Try 6x4d6kh3",
    "The most complex one: 6x4d6+2kh3+2 +2",
    "In D&D your attr. bonus is half of your attr score floored.",
]

# mostly yoinked from https://github.com/radareorg/radare2/blob/master/doc/fortunes.fun and slightly modified
fortunes = [
    "This update didn't hurt any unicorns. Promise.",
    "Stay hydrated!",
    "Give your close ones a call once in a while",
    "Be the guy your 5y/o would look up to!",
    "Do you like prime numbers? You should! >:O",
    "System going down in 60 seconds ... jk :D",
    "Does *this* smell funny?",
    "Are the dishes still waiting to be cleaned?!",
    "A small but regular work out goes a long way.",
    "Why aren't they inviting you for once?",
    "Keep your flat tidy, it keeps your mind clean as well.",
    "Purpose through exhaustion.",
    "When was the last time you went for a walk?",
    "Sadly you have to read the book to obtain its knowledge..",
    "Next time help organising the thing!",
    "Are you still dreaming of her?",
    "Are you still dreaming of him?",
    "You can't sleep now there are monsters nearby",
    "Every journey begins with a choice",
    "Open a door to prove you are not a bot",
    "Sorry, not sorry.",
    "fix it or set the machine on fire",
    "burn it before the bug spreads to other installations",
    "The signals are strong tonight",
    "It's dangerous to go alone, take this.",
    "Watch until the end!",
    "Don't forget to subscribe!",
    "Ah shit, here we go again.",
    "Checking whether this software can be played...",
    "Will it blend?",
    "Mind the trap.",
    "-. .- - .---- / -....- / ... ..- -.-. -.- ... -.-.--",
    "Disassemble?! No Disassemble Johnny No. 5!!!",
    "You crack me up!",
    "Welcome, " + os.getlogin(),
    "Search returned no hits. Did you mean 'Misassemble'?",
    "TIRED OF WAITING",
    "We fix bugs while you sleep.",
    "You find bugs while we sleep.",
    "The stripping process is not deep enough",
    "Come here, we are relatively friendly",
    "Don't wait for Travis",
    "Your problems are solved in an abandoned branch somewhere",
    "git blind --hard",
    "You need some new glasses",
    "aaaa is experimental",
    "We feed trolls",
    "Mind the tab",
    "Gatekeeping something hurts more than it helps.",
    "You have been designated for disassembly",
    "Coffee time!",
    "Can you challenge a perfect immortal machine?",
    "Add more blockchains to your life. lulz. don't.",
    "Congratulations! You got the segfault 1.000.000! Click [here] to win a prize!",
    "Well, it looks like it's working.",
    "There's more than one way to skin a cat",
    "git pull now",
    "git checkout hamster",
    "Noot noot",
    "This is an unregistered copy.",
    "10 reasons you want to bt on all threads - you will be shocked by number 3!",
    "This binary may contain traces of human",
]


def rnd_fortune(): return choice(hints+fortunes)
